language: rust
rust:
  - stable
cache: cargo

env:
  matrix:
    - CI_BUILD_FEATURES="fspecs"

addons:
  apt:
    update: true
    cache: true
    packages:
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev

script:
  - cargo build --features "${CI_BUILD_FEATURES}"
  - cargo test --features "${CI_BUILD_FEATURES}"
